# Generated by Django 4.2 on 2023-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=255, verbose_name='Город')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('now_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Список прогноза погоды',
                'ordering': ['now_dt'],
            },
        ),
    ]
